development:
  adapter: postgresql
  encoding: unicode
  database: cnc_development
  pool: 5
  username: alexandreguignot
  password: 

test:
  adapter: postgresql
  encoding: unicode
  database: cnc_test
  pool: 5
  username: alexandreguignot
  password: 